package com.cti.exception;

public class UsernameAlreadyResponsibleException extends Exception{
}
